# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            # The SSH key fingerprint
            - "25:02:44:e7:4d:0c:f5:ec:81:3a:e6:f8:59:6d:11:ca"
      - run: ls -la ~/repo
      - run: sudo npm i -g yo generator-open-wc
      - run: mkdir asd && cd asd && ls -la && pwd && npm run rungen && ls -la && pwd && echo "/node_modules" > .gitignore && ls -la && cd .. && git remote add testing git@github.com:thepassle/test-output.git && git add . && git commit -m "deploy" && git push testing master


      # https://predictablynoisy.com/circleci-mirror
      # https://discuss.circleci.com/t/in-deployment-trying-to-checkout-merge-in-different-repo-than-build-repo/12459
