# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            # The SSH key fingerprint
            - "00:b3:0e:6e:8a:33:92:a5:41:07:e4:59:f6:16:cc:af"

      - run: git config --global user.email "pascalschilp@gmail.com" && git config --global user.name "thepassle" && git remote add testing git@github.com:thepassle/test-output2.git && npm cache clean --force && ls -la && mkdir foo && cd foo && git clone https://github.com/thepassle/test-output2.git && cd test-output2 && npm init @open-wc starter-app --tag-name=my-app --npm-install=false --scaffold=false && touch ./my-app/asdsad.txt && git status && git add ./my-app/ && git commit -m "deploy3" && git stash && git subtree push --prefix my-app/ testing master

# it doesnt seem to put it in the folder

      # https://predictablynoisy.com/circleci-mirror
      # https://discuss.circleci.com/t/in-deployment-trying-to-checkout-merge-in-different-repo-than-build-repo/12459
