# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ls -la ~/repo
      - run: sudo npm i -g yo generator-open-wc
      # - run: mkdir asd && cd asd && ls -la && npm run rungen && ls -la
      # - run: cd asd
      # - run: npm run rungen
      - run: ls -la
      # run tests
      # - run: npm run test:bs

      # https://predictablynoisy.com/circleci-mirror
      # https://discuss.circleci.com/t/in-deployment-trying-to-checkout-merge-in-different-repo-than-build-repo/12459
