# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            # The SSH key fingerprint
            - "7a:03:51:11:1c:ad:97:b8:4e:29:47:43:78:79:2c:65"
      - run: ls -la ~/repo
      - run: git config --global user.email "pascalschilp@gmail.com" && git config --global user.name "thepassle"
      - run: npm i && ls -la && mkdir foo && cd foo && git pull && rm -rf * && git push --force && ../node_modules/.bin/yo ../node_modules/generator-open-wc/generators/starter-app/ my-app --force && sudo echo "/node_modules" > .gitignore && ls -la && git remote add testing git@github.com:thepassle/test-output.git && cd .. && git add ./foo && git commit -m "deploy2" && git push testing master

it doesnt seem to put it in the folder

      # https://predictablynoisy.com/circleci-mirror
      # https://discuss.circleci.com/t/in-deployment-trying-to-checkout-merge-in-different-repo-than-build-repo/12459
